---
- name: Install Node.js and npm.
  yum:
    name: npm
    state: present
    enablerepo: epel

- name: Install npm modules required by our app
  npm:
    name: "{{item}}"
    global: yes
    state: present
  with_items: "{{node_npm_modules}}"
